export const ADD_LISTING = 'ADD_LISTING'
export const REMOVE_LISTING = 'REMOVE_LISTING'
export const LOGIN = 'LOGIN'
export const LOGOUT = 'LOGOUT'
export const SET_LOADING = 'SET_LOADING'
export const SET_SHOPIFY_ID = 'SET_SHOPIFY_ID'
export const ERROR = 'ERROR'